favicon: /img/favicon.png
# Change to your profile picture
avatar: /img/PaceR_PhotoID.jpg
# if author sets in hexo_config, this string doesn't work
author: 'Rocco Pace'
author_bio: 'PhD (Dr. rer. nat.) - Research fellow -        - @CNR-IRET, Italy #UrbanForestry #EcosystemServices #Modeling'

since: 2022

# Top Menu 顶部菜单
# #title 为页内跳转，单页模式
# 可以选择外链或其他页面
menu:
  Publications: /Publications
  About: /
  #Blog: https://phower.me

# flink picture will load if avator link calls on error
loading_bg:
  flink: /img/profile.png

# Social Links; 社交链接，不需要的链接直接注释掉
# 可以调整显示顺序
# 图标调用 font-awesome 4.7
social:
  enable: true
social_links:
  fab fa-twitter: https://twitter.com/RoccoPace2
  fab fa-facebook-square: https://www.facebook.com/rocco.pace.33
  fab fa-github: https://github.com/Rocpp
  #fab fa-stack-overflow: /
  fab fa-linkedin: https://www.linkedin.com/in/rocco-pace-7a47b4106/
  #fab fa-weibo: /
  #fab fa-weixin: /
  #fab fa-qq: /
  #fas fa-envelope: / #E-mail
  #fas fa-rss: /  #rss

# Additional social_links，额外添加自定义链接，可显示链接名称
# name: url || icon_name
e_social:
  enable: true
e_social_links:
  Google Scholar: https://scholar.google.it/citations?user=https://scholar.google.com/citations?hl=it&user=L7K-wGQAAAAJ || fas fa-graduation-cap
  ORCID: https://orcid.org/0000-0002-3126-635X || fab fa-orcid
  Researchgate: https://www.researchgate.net/profile/Rocco-Pace || fab fa-researchgate
  Scopus Author ID: https://www.scopus.com/authid/detail.uri?authorId=57200690575 || fab fa-scopus
  WoS Researcher ID: https://publons.com/researcher/3933120/rocco-pace/ || fab fa-WoS

# CV download link
cv_dl:
  enable: true
  dir: /attaches/CV.pdf
  description: My Detail CV.

# Box-shadow
# display box-shadow on page or not
box_shadow:
  enable: false

# CDN
# 根据需要自行添加js/css
# 自定义css可以直接写在user.styl中
CDN_USE:
  css:
    - /css/index.css
#    - https://cdn.jsdelivr.net/npm/font-awesome@latest/css/font-awesome.min.css
    - https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.0/css/all.min.css # fontawesome 5
  js:
    - https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js #/js/third-party/jquery.min.js
    - https://cdn.jsdelivr.net/npm/jquery-pjax@latest/jquery.pjax.min.js
    - /js/main.js